services:
  - type: web
    name: bot-sofia
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 main:app"

    # A variável 'nome_do_arquivo' deve ser substituída pelo nome do seu script, sem a extensão .py
